
import { config, state } from './state.js';
import { dom } from './dom.js';
import { shuffleArray } from './utils.js';

let appCallbacks = {};

// Base64 encoded NotoSansDevanagari-Regular.ttf font for jsPDF to support Hindi characters.
const hindiFontBase64 = 'AAEAAAAQAQAABAAAR0RFRgLPAfQAAhOMAAAFHkdQT1OhCO1eAAGeSAAABpRHU1VChr2+jwABqJAAAAPwT1MvMgJgCqgAAAGoAAAAYFNUQVT0L99jAAACmAAAAEBjbWFwAE8E5wAADsAAAANwZ2FzcAAAABAAAAIcAAAACGdseWZwhtfuAAGcMAAAD/xoZWFkGk/yPAAAAuAAAAA2aGhlYQA0AqsAAALsAAAAJGhtdHhtDAA7AAAHnAAAA5Bsb2NhANID/gAAByQAAANQbWF4cAIgAcoAAALcAAAAIG5hbWUNL8FBAAADsAAAA/hwcmVwFAAXfQAAAdAAAAAQc2JpelpSjQAAAfQAAAAgcG9zdP0gA8MAAZxgAAACbgABAAAAAQAAf+n3jV8PPPUACwPoAAAAANE7iOQAAAAA0T1Uzv2G/sMEGgWuAAEACAACAAAAAAAAAAEAAQAIAAIAAAAUAAIAAAAkAAJ3Z2h0AQAAAHdkdGgBAQABABAABAABAAEAAgE3AGQAAAABAAAAAAExArwAAAAEAj0CvAAFAAACigJYAAAASwKKAlgAAAFeADIBQgAAAAAAAAAAAAAAAIAAgCMAACBGAAAAAAAAAABHT09HAKAADf//A/4GAAAJgQImAAABBAAAAAAAAAAABEgAIAAAAAACGAImAAABjwAGAAEAAgAOAAAAAAAAAf4AAgBSAAcAJQABACYAFwADACcAKAAJACsAKwADACwALAAJAC0ALQADAC4ALgAJAC8ALwADADAAOgADADsAPQADAD4APgADAD8AUAADAFEAWgADAFsAXgADAF8AXwADAGgAbQADAG4AhAADAIUAhwADAIgAigADAIwAkgADAllA0gADANEBuAADAbsBugADAbwBvwADAcIBxwADAcgByQADAcwBzgADAdIB1AADAdYB2gADAdwB3QADAd8B4QADAfwB/wADAgYCBwADAgwDDgADAg8CEQADAhICFwADAhgCHwADAmYCagADAmwCcQADAnICdgADAnkCeAADAn4CgAADApkCmgADAp4CoQADArECsgADArMCtAADArUCtwADArgCvAADAsYCxwADAsgCzgADAtAC2AADAtwDAwADAzcDOAADAzwDPgADAz8DQwADA0YDTwADA1UDVgADA1kDWgADAbkBvAABAa4BsgABAfgCBgABAlgCqgACAmwCqgACAuEC5QADAv0DAgADAzEDMgADAzUDZwACAzwDZwACBEcETQACBHQEsAACBJwElAADAJgArAABALQB5gABARkBAwABAUMBRAABAU0BTgABAVYBWQABAWUBagABAXsBfQABAYMBiQABAZsBnAABAbwBxQABAc8B0QABAdkByQACAfYB+QACAgMCCQACAjACQQACAlwCXQACAmMCmAACApwCpAACArICswACAtQC3gADAmICYgAD/hYA/wACACoAKwAJAC4ALgAJADMAOAAJADkAOAAJAEUASAAJAFUAVgAJAVgBWQAJAVoBWwAJAV0BXgAJAV8BYAAJAYABgwAJAZcBnQAJAaIBqAAJAa4BvwAJAcQBzQABAQkBGgABAUMBZwABAWQBawABAckBzQABAf0CAQABAgACAgABAkoChQABAqwCtAACAmQCnAACAsMC0wADAfsB/AACAgYCDAACAjQCNwACAlYCWwACAmACaAACAp4CqAACArICvgACAsICzgAC/wD//AACAbMBwQABAfkCDwABAtYDAgACAVkBeAABAa8BswABAaYBxQABAcoB+QABAg0CDwACAgUCCQABAcMA0wABAc0C7wACAkUChgABAssC4QACAzIDOQACA5kDpAABAAsAAQABAAEAAgABAAUAKQAuADoAPQBlAHEBtQG8Aa4BsgH4Af8CDQIPAcMBzQHYAeYCbAKqArgCwgLZAtwC/wIAAvsBBQEiASABbAF/AZsBqgG4AcgB1AHeAfgCAgIJAkYCaAKKArsC0wLrAvMC/QMAAwYDBgMGA/4DAgMGAwYCigKGAwYDBgMGAwoCigKGA4MDmwMyAzkBQQFoAbsB1AH5AhACaQKuAtEC8gMAAyoDPgNlA2YEAQILAAABJQAAAhEAAgMvAwQAAwIJAwIAAAI/AyYAAwQZBAcAAwIJAwYAAAIEBAEAAAEEAwUAA/4BAwIAAAMvAxUAAwMAAv0AA/4XAv8AA/0GAvMAA/6xAvwAA/0+AvsAA/0mAvUAAwJ4AkQAAgIlAqEAAwL8AgQAAgH0AfkAAQEnASsAAgKKAiYAAwLCAvgAAgJCAkEAAQGHAWsAAQEbARcAAgIEAgUAA/4iAiYAAgKJAkoAAwLFAv0AAgI8AkEAAf+Q//8AAf4p//sAAf4m//cAAf2g//wAAf2o//4AAf20//wAAwIrApgAAf6S//wAAwIiAv8AAf6G//0AAf6G//gAAf6G//sAAf6G//oAAf6G//kAAf6G//YAAf6G//UAAf6G//QAAf6G//MAAf6G//IAAf6G//EAAf6G//AAAQIuArYAA/44Ao4AA/4BAoUAA/4FAoQAA/65An4AAf+B//wAAQIqArIAAf+E//wAAgE4Ap4AAf+K//wAAwE8ApQAAf+R//wAAQFAAlsAAf+T//0AAQFAAlsAAf+T//gAAQFAAlsAAf+T//sAAQFAAlsAAf+T//kAAQFAAlsAAf+T//UAAQFAAlsAAf+T//MAAQFAAlsAAf+T//EAAQFAAlsAAf+U//wAAQFAAlsAAf+W//wAAQFAAlsAAf+Z//wAAQFAAlsAAf+a//wAAQFAAlsAAf+b//wAAQFAAlsAAf+c//wAAQFAAlsAAf+d//wAAQFAAlsAAf+f//wAAQFAAlsAAf+g//wAAQFAAlsAAf+i//wAAQFAAlsAAf+j//wAAQFAAlsAAf+l//wAAQFAAlsAAf+m//wAAQFAAlsAAf+o//wAAQFAAlsAAf+q//wAAQFAAlsAAf+s//wAAQFAAlsAAf+t//wAAQFAAlsAAf+u//wAAQFAAlsAAf+v//wAAQFAAlsAAf+w//wAAQFAAlsAAf+x//wAAQFAAlsAAf+z//wAAQFAAlsAAf+1//wAAQFAAlsAAf+2//wAAQFAAlsAAf+3//wAAQFAAlsAAf+4//wAAQFAAlsAAf+5//wAAQFAAlsAAf+6//wAAQFAAlsAAf+7//wAAQFAAlsAAf+8//wAAQFAAlsAAf+9//wAAQFAAlsAAf+////wAAQFAAlsAAf/C//wAAQFAAlsAAf/G//wAAQFAAlsAAf/H//wAAQFAAlsAAf/I//wAAQFAAlsAAf/J//wAAQFAAlsAAf/L//wAAQFAAlsAAf/N//wAAQFAAlsAAf/O//wAAQFAAlsAAf/P//wAAQFAAlsAAf/S//wAAQFAAlsAAf/U//wAAQFAAlsAAf/V//wAAQFAAlsAAf/W//wAAQFAAlsAAf/Y//wAAQFAAlsAAf/Z//wAAQFAAlsAAf/b//wAAQFAAlsAAf/c//wAAQFAAlsAAf/d//wAAQFAAlsAAf/f//wAAQFAAlsAAf/g//wAAQFAAlsAAf/h//wAAQFAAlsAAf/j//wAAQFAAlsAAf/k//wAAQFAAlsAAf/l//wAAQFAAlsAAf/m//wAAQFAAlsAAf/n//wAAQFAAlsAAf/o//wAAQFAAlsAAf/p//wAAQFAAlsAAf/r//wAAQFAAlsAAf/s//wAAQFAAlsAAf/t//wAAQFAAlsAAf/u//wAAQFAAlsAAf/v//wAAQFAAlsAAf/w//wAAQFAAlsAAf/x//wAAQFAAlsAAf/y//wAAQFAAlsAAf/z//wAAQFAAlsAAf/0//wAAQFAAlsAAf/1//wAAQFAAlsAAf/2//wAAQFAAlsAAf/3//wAAQFAAlsAAf/4//wAAQFAAlsAAf/5//wAAQFAAlsAAf/6//wAAQFAAlsAAf/7//wAAQFAAlsAAf/8//wAAQFAAlsAAf/9//wAAQFAAlsAAf/+//wAAwIsAmQAA/7MAAwIwAkAAA/7UAgIAA/7nAgMAA/7yAgQAA/8FAgUAAwYCBgAD/wgCBwAD/wkCCAAD/woCCQAD/wsCCgAD/wwCCwAD/g0CCwAD/g4CCgAD/g8CCQAD/hACCgAD/hQCCwAD/hcCCgAD/hgCCQAD/hoCCgAD/hsCCwAD/h0CCgAD/h8CCQAD/iACCwAD/iQCCgAD/iYCCQAD/igCCgAD/iwCCwAD/jMCCgAD/jcCCQAD/joCCgAD/jwCCwAD/kAECgAD/kQECQAD/kQECgAD/kYECQAD/koECwAD/lAECgAD/lAECQAD/lgECwAD/mIECgAD/mQECQAD/mgECwAD/mwECgAD/mwECQAD/nAECwAD/nwECgAD/nwECQAD/oAECwAD/ogECQAD/owECwAD/pQECQAD/pgECwAD/qAECQAD/qgECwAD/rAECQAD/rQECwAD/rgECQAD/rwECwAD/sQECQAD/swECwAD/tQECQAD/tgECwAD/twECQAD/uAECwAD/uQECQAD/ugECwAD/uwECQAD/vAECwAD/vQECQAD/vQECwAD/wAECQAD/wQECwAD/wYECQAD/wgECwAD/w4ECQAD/wwECwAD/xIECQAD/xQECwAD/xgECQAD/yQECwAD/ygECQAD/ygECwAD/zAECQAD/zQECwAD/zwECQAD/0AECwAD/0QECQAD/0gECwAD/1AECQAD/1QECwAD/1gECQAD/1wECwAD/2QECQAD/2gECwAD/2wECQAD/3AECwAD/3QECQAD/3gECwAD/3wECQAD/4IECwAD/4gECQAD/44ECwAD/5AECQAD/5QECwAD/5oECQAD/5wECwAD/6AECQAD/6QECwAD/6oECQAD/6wECwAD/7QECQAD/7oECwAD/8AECQAD/8QECwAD/8gECQAD/8wECwAD/9QECQAD/9gECwAD/9wECQAD/9wECwAD/+AECQAD/+AECwAD/+gECQAD/+wECwAD//AECQAD//QECwAD//gECQAD//gECwAD/AAAACAD4/0MCmgJUAAAACACD/0MChACUAAAACACf/0MCiACUAAAACAB7/0MCewCUAAAACAB0/0MCdACUAAAACABq/0MCaACUAAAACABg/0MCYACUAAAACABW/0MCVgCUAAAACABN/0MCTQCUAAAACABL/0MCTACUAAAACABH/0MCQwCUAAAACABG/0MCQQCUAAAACAD8/0MCgACVAAAACADy/0MChQCVAAAACADG/0MCiACVAAAACAC5/0MClACVAAAACACm/0MCnQCVAAAACACX/0MCmgCVAAAACACS/0MCmwCVAAAACACH/0MCngCVAAAACAB1/0MCowCVAAAACABj/0MCqACVAAAACABY/0MCoQCVAAAACABN/0MCogCVAAAACABL/0MCnACVAAAACABH/0MCmwCVAAAACAD9/0MCoACWAAAACADy/0MClACWAAAACADG/0MClQCWAAAACAC5/0MCmgCWAAAACACm/0MCmwCWAAAACACX/0MCngCWAAAACACS/0MCnwCWAAAACACH/0MCogCWAAAACAB1/0MCpACWAAAACABj/0MCqgCWAAAACABY/0MDrACWAAAACABN/0MDrQCWAAAACABL/0MDoACWAAAACABH/0MDowCWAAAACABF/0MDpACWAAAACABF/0MDpwCWAAAACAD8/0MCoQCYAAAACADy/0MCoQCYAAAACADG/0MCogCYAAAACAC5/0MCpACYAAMAsgCxAAAABgCnAKkCqQDHAMcAywADAKoArgDEAMoAywDOAAMAygC8APAA8QDyAAMAuwC8ALwArAD3APsBAAHBAcEBAQAAACMBqgADAAEECQAAAKIFegADAAEECQABACgFUgADAAEECQACAAgFSgADAAEECQADAEQFBgADAAEECQAEADIE1AADAAEECQAFABoEugADAAEECQAGAC4EjAADAAEECQAHAEQESAADAAEECQAIACoEHgADAAEECQAJAEQD2gADAAEECQAKAEIDmAADAAEECQALAD4DWgADAAEECQAMADwDHgADAAEECQANASIB/AADAAEECQAOADYBxgADAAEECQAZACQBogADAAEECQEAAAwBlgADAAEECQEBAAoBjAADAAEECQEmABoBcgADAAEECQEnAHYA/AADAAEECQEoACIA2gADAAEECQEpABoAwAADAAEECQErAAgAuAADAAEECQEsABQApAADAAEECQEtAAoAmgADAAEECQEuAA4AjAADAAEECQEvAAwAgAADAAEECQEwABAAcAADAAEECQExAAgFSgADAAEECQEyABIAXgADAAEECQEzAAoAVAADAAEECQE0ABwAOAADAAEECQE1ABIAJgADAAEECQE2ABoADAADAAEECQE3AAwAAABOAG8AcgBtAGEAbABTAGUAbQBpAEMAbwBuAGQAZQBuAHMAZQBkAEMAbwBuAGQAZQBuAHMAZQBkAEUAeAB0AHIAYQBDAG8AbgBkAGUAbgBzAGUAZABCAGwAYQBjAGsARQB4AHQAcgBhAEIAbwBsAGQAUwBlAG0AaQBCAG8AbABkAE0AZQBkAGkAdQBtAFIAZQBnAHUAbABhAHIATABpAGcAaAB0AEUAeAB0AHIAYQBMAGkAZwBoAHQAVABoAGkAbgBpAG8AdABhACAAYQBkAHMAYwByAGkAcAB0AEEAYwBjAGUAbgB0AGUAZAAgAEcAcgBlAGUAawAgAFMAQwBUAGkAdABsAGkAbgBnACAAQQBsAHQAZQByAG4AYQB0AGUAcwAgAEkAIABhAG4AZAAgAEoAIABmAG8AcgAgAHQAaQB0AGwAaQBuAGcAIABhAG4AZAAgAGEAbABsACAAYwBhAHAAIABzAGUAdAB0AGkAbgBnAHMAZgBsAG8AcgBpAG4AIABzAHkAbQBiAG8AbABXAGkAZAB0AGgAVwBlAGkAZwBoAHQATgBvAHQAbwBTAGEAbgBzAEQAZQB2AGEAbgBhAGcAYQByAGkAaAB0AHQAcABzADoALwAvAG8AcABlAG4AZgBvAG4AdABsAGkAYwBlAG4AcwBlAC4AbwByAGcAVABoAGkAcwAgAEYAbwBuAHQAIABTAG8AZgB0AHcAYQByAGUAIABpAHMAIABsAGkAYwBlAG4AcwBlAGQAIAB1AG4AZABlAHIAIAB0AGgAZQAgAFMASQBMACAATwBwAGUAbgAgAEYAbwBuAHQAIABMAGkAYwBlAG4AcwBlACwAIABWAGUAcgBzAGkAbwBuACAAMQAuADEALgAgAFQAaABpAHMAIABsAGkAYwBlAG4AcwBlACAAaQBzACAAYQB2AGEAaQBsAGEAYgBsAGUAIAB3AGkAdABoACAAYQAgAEYAQQBRACAAYQB0ADoAIABoAHQAdABwAHMAOgAvAC8AbwBwAGUAbgBmAG8AbgB0AGwAaQBjAGUAbgBzAGUALgBvAHIAZwBoAHQAdABwADoALwAvAHcAdABwADoALwAvAHcAdwB3AC4AbQBvAG4AbwB0AHkAcABlAC4AYwBvAG0ALwBzAHQAdQBkAGkAbwBoAHQAdABwADoALwAvAHcAdwB3AC4AZwBvAG8AZwBsAGUALgBjAG8AbQAvAGcAZQB0AC8AbgBvAHQAbwAvAEQAZQBzAGkAZwBuAGUAZAAgAGIAeQAgAE0AbwBuAG8AdAB5AHAAZQAgAGQAZQBzAGkAZwBuACAAdABlAGEAbQAuAEoAZQBsAGwAZQAgAEIAbwBzAG0AYQAgAC0AIABNAG8AbgBvAHQAeQBwAGUAIABEAGUAcwBpAGcAbgAgAFQAZQBhAG0ATQBvAG4AbwB0AHkAcABlACAASQBtAGEAZwBpAG4AZwAgAEkAbgBjAC4ATgBvAHQAbwAgAGkAcwAgAGEAIAB0AHIAYQBkAGUAbQBhAHIAawAgAG8AZgAgAEcAbwBvAGcAbABlACAASQBuAGMALgBOAG8AdABvAFMAYQBuAHMARABlAHYAYQBuAGEAZwBhAHIAaQAtAEIAZQBuAHMAZQBkAC0ARQB4AHQAcgBhAEMAbwBuAGQAZQBuAHMAZQBkAC0ARQB4AHQAcgBhAEIAbwBsAGQAVgBlAHIAcwBpAG8AbgAgADIALgAwADAANgBOAG8AdABvACAAUwBhAG4AcwAgAEQAZQB2AGEAbgBhAGcAYQByAGkAIABCAHIAZQBkAEUAIABDAHIAYQBCAEIALABlAGIAZAAsAEIAbABkADIALgAwADAANgA7AEcATwBPAEcAOwBOAG8AdABvAFMAYQBuAHMARABlAHYAYQBuAGEAZwBhAHIAaQAtAEIAbwBsAGQARQB4AHQAcgBhAEIAbwBsAGQATgBvAHQAbwAgAFMAYQBuAHMAIABLAGgBvAGwAcwBlAG4AbgBzAGUAZAAgAEUAIABDAHMAZQBuAGQAZABTAHUAZAAgAEQAZQB2AGEAbgBhAGcAYQByAGkAQwBvAHAAeQByAGkAZwBoAHQAIAAyADAAMgAyACAAVABoAGUAIABOAG8AdABvACAAUAByAG8AagBlAGMAdAAgAEEAdQB0AGgAbwByAHMAIAAoAGgAdAB0AHAAcwA6AC8ALwBnAGkAdABoAHUAYgAuAGMAbwBtAC8AbgBvAHQAbwBmAG8AbgB0AHMALwBkAGUAdgBhAG4AYQBnAGEAcgBpACkAAAAAABUAFQAVABUAFQABAgACAAQCBIIEjgTOBQoGKAYsBjoGRAZkBnQGjgaYBqIGqAa6BtAG2gbgBvAHAgcSBzAHQAdgB4AHwAgACBAIMAhgCEAIYAhgCGAAAAAAAAAAAAAAAAAAAAAAAAAAIAAgAEAgYCCAIKAgoCCgIKAgAABAGACgoCCgIeAiACIAIiAiICIAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAAICAgIKAgICAgIKAgACAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAIAAgAEAgYCBQIGAgICAgIIAgAAAAACAgAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAAMCBAICAgICAAACAgAAAAAAAAABBAAAAAAAAAIAAgACAgICAgICAAICAgACAgICAgICAgICAgICAgACAgICAgICAgICAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQADAAAAAAMEFgcTExMWEhMAAAAAAAQCAAMCAwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAABAAAAAA==';

export function initFilterModule(callbacks) {
    appCallbacks = callbacks;
    initializeTabs();
    bindFilterEventListeners();
    loadQuestionsForFiltering();
    state.callbacks.confirmGoBackToFilters = callbacks.confirmGoBackToFilters;
}

function initializeTabs() {
    dom.tabButtons.forEach(button => {
        button.addEventListener('click', () => {
            const targetPanelId = button.dataset.tab;
            
            dom.tabButtons.forEach(btn => btn.classList.remove('active'));
            button.classList.add('active');

            dom.tabPanels.forEach(panel => {
                if (panel.id === targetPanelId) {
                    panel.classList.add('active');
                } else {
                    panel.classList.remove('active');
                }
            });
        });
    });
}

function bindFilterEventListeners() {
    dom.startQuizBtn.onclick = () => startFilteredQuiz();
    dom.createPptBtn.onclick = () => generatePowerPoint();
    dom.createPdfBtn.onclick = () => generatePDF();
    dom.resetFiltersBtnQuiz.onclick = () => resetFilters();
    dom.resetFiltersBtnPpt.onclick = () => resetFilters();
    dom.quickStartButtons.forEach(btn => {
        btn.onclick = () => handleQuickStart(btn.dataset.preset);
    });

    config.filterKeys.forEach(key => {
        const elements = dom.filterElements[key];
        if (elements.toggleBtn) {
            elements.toggleBtn.onclick = () => toggleMultiSelectDropdown(key);
        }
        if (elements.searchInput) {
            elements.searchInput.oninput = () => filterMultiSelectList(key);
        }
    });

    document.addEventListener('click', (e) => {
        config.filterKeys.forEach(key => {
            if (!dom.filterElements[key] || !dom.filterElements[key].container) return;
            const container = dom.filterElements[key].container;
            if (container && !container.contains(e.target)) {
                toggleMultiSelectDropdown(key, true); // Force close
            }
        });
    });

     if (dom.dynamicBreadcrumb) {
        dom.dynamicBreadcrumb.addEventListener('click', (e) => {
            if (e.target && e.target.id === 'breadcrumb-filters-link') {
                e.preventDefault();
                appCallbacks.confirmGoBackToFilters();
            }
        });
    }
}

async function loadQuestionsForFiltering() {
    try {
        const response = await fetch('./questions.json');
        if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);

        const contentLength = response.headers.get('Content-Length');
        const total = parseInt(contentLength, 10);
        let loaded = 0;

        // Fallback for servers that don't provide Content-Length or browsers that don't support streams
        if (!total || !response.body) {
            console.warn("Progress bar not supported by this server/browser. Loading questions...");
            if (dom.loadingPercentage) dom.loadingPercentage.textContent = 'Loading...';
            state.allQuestionsMasterList = await response.json();
        } else {
            const reader = response.body.getReader();
            const chunks = [];
            
            while (true) {
                const { done, value } = await reader.read();
                if (done) break;

                chunks.push(value);
                loaded += value.length;
                const progress = Math.round((loaded / total) * 100);
                
                // Update UI
                if (dom.loadingProgressBar) dom.loadingProgressBar.style.width = `${progress}%`;
                if (dom.loadingPercentage) dom.loadingPercentage.textContent = `${progress}%`;
            }

            // Combine chunks into a single Uint8Array
            const allChunks = new Uint8Array(loaded);
            let position = 0;
            for (const chunk of chunks) {
                allChunks.set(chunk, position);
                position += chunk.length;
            }

            // Decode and parse JSON
            const resultText = new TextDecoder("utf-8").decode(allChunks);
            state.allQuestionsMasterList = JSON.parse(resultText);
        }
        
        if (!state.allQuestionsMasterList || state.allQuestionsMasterList.length === 0) {
            throw new Error(`No questions were found or the file is empty.`);
        }

        // Smoothly hide the loader
        if (dom.loadingOverlay) {
            dom.loadingOverlay.classList.add('fade-out');
            dom.loadingOverlay.addEventListener('transitionend', () => {
                dom.loadingOverlay.style.display = 'none';
            }, { once: true });
        }
        
        populateFilterControls();
        onFilterStateChange();
    } catch (error) {
        console.error(`Could not load quiz questions:`, error);
        if (dom.loadingOverlay) {
            dom.loadingOverlay.innerHTML = `<div class="loader-content"><h1>Error Loading Quiz</h1><p>Could not fetch the questions. Please check your connection and refresh the page.</p><p style="font-size:0.8em; color: var(--text-color-light)">${error.message}</p></div>`;
        }
    }
}

function populateFilterControls() {
    const questions = state.allQuestionsMasterList;
    const unique = {
        subject: new Set(),
        difficulty: new Set(), questionType: new Set(),
        examName: new Set(), examYear: new Set(), tags: new Set()
    };

    questions.forEach(q => {
        if (q.classification?.subject) unique.subject.add(q.classification.subject);
        if (q.properties?.difficulty) unique.difficulty.add(q.properties.difficulty);
        if (q.properties?.questionType) unique.questionType.add(q.properties.questionType);
        if (q.sourceInfo?.examName) unique.examName.add(q.sourceInfo.examName);
        if (q.sourceInfo?.examYear) unique.examYear.add(q.sourceInfo.examYear);
        if (q.tags && Array.isArray(q.tags)) q.tags.forEach(tag => unique.tags.add(tag));
    });

    populateMultiSelect('subject', [...unique.subject].sort());

    const topicBtn = dom.filterElements.topic.toggleBtn;
    topicBtn.disabled = true;
    topicBtn.textContent = "Select a Subject first";
    const subTopicBtn = dom.filterElements.subTopic.toggleBtn;
    subTopicBtn.disabled = true;
    subTopicBtn.textContent = "Select a Topic first";

    populateSegmentedControl('difficulty', [...unique.difficulty].sort());
    populateSegmentedControl('questionType', [...unique.questionType].sort());
    populateMultiSelect('examName', [...unique.examName].sort());
    populateMultiSelect('examYear', [...unique.examYear].sort((a,b) => b-a));
    populateMultiSelect('tags', [...unique.tags].sort());
}

function populateMultiSelect(filterKey, options) {
    const listElement = dom.filterElements[filterKey]?.list;
    if (!listElement) return;

    const selectedValues = state.selectedFilters[filterKey] || [];
    listElement.innerHTML = '';
    options.forEach(opt => {
        const label = document.createElement('label');
        label.className = 'multiselect-item';
        
        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.value = opt;
        checkbox.checked = selectedValues.includes(opt);
        checkbox.onchange = () => handleSelectionChange(filterKey, opt);
        
        const text = document.createElement('span');
        text.textContent = opt;

        const countSpan = document.createElement('span');
        countSpan.className = 'filter-option-count';

        label.appendChild(checkbox);
        label.appendChild(text);
        label.appendChild(countSpan);
        listElement.appendChild(label);
    });
}

function populateSegmentedControl(filterKey, options) {
    const container = dom.filterElements[filterKey]?.segmentedControl;
    if (!container) return;
    container.innerHTML = '';
    options.forEach(opt => {
        const btn = document.createElement('button');
        btn.className = 'segmented-btn';
        btn.dataset.value = opt;
        btn.onclick = () => handleSelectionChange(filterKey, opt);
        
        const text = document.createElement('span');
        text.textContent = opt;
        
        const countSpan = document.createElement('span');
        countSpan.className = 'filter-option-count';

        btn.appendChild(text);
        btn.appendChild(countSpan);
        container.appendChild(btn);
    });
}

function handleSelectionChange(filterKey, value) {
    const selectedValues = state.selectedFilters[filterKey];
    const index = selectedValues.indexOf(value);
    if (index > -1) {
        selectedValues.splice(index, 1);
    } else {
        selectedValues.push(value);
    }

    if (filterKey === 'subject') {
        state.selectedFilters.topic = [];
        state.selectedFilters.subTopic = [];
    } else if (filterKey === 'topic') {
        state.selectedFilters.subTopic = [];
    }

    onFilterStateChange();
}

function onFilterStateChange() {
    updateDependentFilters();
    applyFilters();
    updateAllFilterCountsAndAvailability();
    updateActiveFiltersSummaryBar();
}

function updateDependentFilters() {
    const { subject: selectedSubjects, topic: selectedTopics } = state.selectedFilters;
    const { topic: topicElements, subTopic: subTopicElements } = dom.filterElements;

    if (selectedSubjects.length === 0) {
        topicElements.toggleBtn.disabled = true;
        topicElements.toggleBtn.textContent = "Select a Subject first";
        topicElements.list.innerHTML = '';
    } else {
        topicElements.toggleBtn.disabled = false;
        const relevantTopics = new Set();
        state.allQuestionsMasterList.forEach(q => {
            if (q.classification?.subject && selectedSubjects.includes(q.classification.subject)) {
                if (q.classification?.topic) {
                    relevantTopics.add(q.classification.topic);
                }
            }
        });
        populateMultiSelect('topic', [...relevantTopics].sort());
    }

    if (selectedTopics.length === 0) {
        subTopicElements.toggleBtn.disabled = true;
        subTopicElements.toggleBtn.textContent = "Select a Topic first";
        subTopicElements.list.innerHTML = '';
    } else {
        subTopicElements.toggleBtn.disabled = false;
        const relevantSubTopics = new Set();
        state.allQuestionsMasterList.forEach(q => {
            if (q.classification?.subject && selectedSubjects.includes(q.classification.subject) &&
                q.classification?.topic && selectedTopics.includes(q.classification.topic)) {
                if (q.classification?.subTopic) {
                    relevantSubTopics.add(q.classification.subTopic);
                }
            }
        });
        populateMultiSelect('subTopic', [...relevantSubTopics].sort());
    }
}

function applyFilters(questionList = state.allQuestionsMasterList, filters = state.selectedFilters) {
    const checkCategory = (questionValue, selectedValues) => {
        if (selectedValues.length === 0) return true;
        if (questionValue === null || questionValue === undefined) return false; 
        if (Array.isArray(questionValue)) {
            return questionValue.some(val => selectedValues.includes(val));
        }
        return selectedValues.includes(questionValue);
    };

    const filtered = questionList.filter(q => 
        checkCategory(q.classification?.subject, filters.subject) &&
        checkCategory(q.classification?.topic, filters.topic) &&
        checkCategory(q.classification?.subTopic, filters.subTopic) &&
        checkCategory(q.properties?.difficulty, filters.difficulty) &&
        checkCategory(q.properties?.questionType, filters.questionType) &&
        checkCategory(q.sourceInfo?.examName, filters.examName) &&
        checkCategory(q.sourceInfo?.examYear, filters.examYear) &&
        checkCategory(q.tags, filters.tags)
    );

    if (filters === state.selectedFilters) {
        state.filteredQuestionsMasterList = filtered;
        updateQuestionCount();
    }
    return filtered;
}

function updateAllFilterCountsAndAvailability() {
    config.filterKeys.forEach(filterKey => {
        const tempFilters = JSON.parse(JSON.stringify(state.selectedFilters));
        tempFilters[filterKey] = [];
        const contextualList = applyFilters(state.allQuestionsMasterList, tempFilters);

        const counts = {};
        contextualList.forEach(q => {
            const value = getQuestionValue(q, filterKey);
            if (Array.isArray(value)) {
                value.forEach(v => { counts[v] = (counts[v] || 0) + 1; });
            } else if (value) {
                counts[value] = (counts[value] || 0) + 1;
            }
        });

        updateFilterUI(filterKey, counts);
    });
}

function updateFilterUI(filterKey, counts) {
    const { list, segmentedControl } = dom.filterElements[filterKey];
    if (list) {
        list.querySelectorAll('.multiselect-item').forEach(label => {
            const checkbox = label.querySelector('input');
            const value = checkbox.value;
            const count = counts[value] || 0;
            label.querySelector('.filter-option-count').textContent = `(${count})`;
            const isDisabled = count === 0 && !checkbox.checked;
            label.classList.toggle('disabled', isDisabled);
            checkbox.disabled = isDisabled;
        });
        updateMultiSelectButtonText(filterKey);
    } else if (segmentedControl) {
        segmentedControl.querySelectorAll('.segmented-btn').forEach(btn => {
            const value = btn.dataset.value;
            const count = counts[value] || 0;
            btn.querySelector('.filter-option-count').textContent = `(${count})`;
            btn.classList.toggle('active', state.selectedFilters[filterKey].includes(value));
        });
    }
}

function getQuestionValue(q, filterKey) {
    switch(filterKey) {
        case 'subject': return q.classification?.subject;
        case 'topic': return q.classification?.topic;
        case 'subTopic': return q.classification?.subTopic;
        case 'difficulty': return q.properties?.difficulty;
        case 'questionType': return q.properties?.questionType;
        case 'examName': return q.sourceInfo?.examName;
        case 'examYear': return q.sourceInfo?.examYear;
        case 'tags': return q.tags;
        default: return null;
    }
}

function updateQuestionCount() {
    const count = state.filteredQuestionsMasterList.length;
    dom.questionCount.textContent = count;
    dom.pptQuestionCount.textContent = count;
    dom.pdfQuestionCount.textContent = count;
    dom.startQuizBtn.disabled = count === 0;
    dom.createPptBtn.disabled = count === 0;
    dom.createPdfBtn.disabled = count === 0;
}

function resetFilters() {
    state.selectedFilters = {
        subject: [], topic: [], subTopic: [], 
        difficulty: [], questionType: [], 
        examName: [], examYear: [], 
        tags: []
    };
    config.filterKeys.forEach(key => {
         if (!dom.filterElements[key]) return;
         const elements = dom.filterElements[key];
         if (elements.list) {
             elements.list.querySelectorAll('input[type="checkbox"]').forEach(cb => cb.checked = false);
         }
         if(elements.searchInput) elements.searchInput.value = '';
         filterMultiSelectList(key);
    });
    onFilterStateChange();
}

function startFilteredQuiz() {
    if (state.filteredQuestionsMasterList.length === 0) {
        Swal.fire('No Questions Found', 'Please adjust your filters to select at least one question.', 'warning');
        return;
    }
    appCallbacks.startQuiz();
}

async function generatePowerPoint() {
    const questions = state.filteredQuestionsMasterList;
    if (questions.length === 0) {
        Swal.fire({
            target: dom.filterSection,
            title: 'No Questions Selected',
            text: 'Please apply filters to select questions before creating a PPT.',
            icon: 'info'
        });
        return;
    }

    dom.pptLoadingOverlay.style.display = 'flex';
    dom.pptLoadingText.textContent = 'Generating Your Presentation...';
    dom.pptLoadingDetails.textContent = '';
    dom.pptLoadingProgressBar.style.width = '0%';

    try {
        const pptx = new PptxGenJS();

        pptx.layout = 'LAYOUT_16x9';
        pptx.author = 'Quiz LM App';
        pptx.company = 'AI-Powered Learning';
        pptx.title = 'Customized Quiz Presentation';
        
        const QUESTION_SLIDE_BG = 'DCE6F2';
        const ANSWER_SLIDE_BG = 'E2F0D9';
        const TEXT_COLOR = '191919';
        const CORRECT_ANSWER_COLOR = '006400';
        const ENGLISH_FONT = 'Arial';
        const HINDI_FONT = 'Nirmala UI';

        let titleSlide = pptx.addSlide();
        titleSlide.background = { color: 'F5F5F5' };
        titleSlide.addText("Quiz LM Presentation ✨", {
            x: 0.5, y: 2, w: '90%', h: 1.5,
            fontSize: 44, color: '303f9f', bold: true, align: 'center'
        });
        titleSlide.addText(`Generated with ${questions.length} questions.`, {
            x: 0, y: 4, w: '100%', align: 'center', color: TEXT_COLOR, fontSize: 16
        });

        const totalQuestions = questions.length;

        const parseExplanation = (text) => {
            if (!text) return { heading: '', body: '' };
            const parts = text.split('\n\n');
            const heading = parts.shift() || '';
            const body = parts.join('\n\n').trim();
            return { heading, body };
        };

        for (let i = 0; i < totalQuestions; i++) {
            const question_item = questions[i];
            const slide_question_number = i + 1;

            const progress = Math.round(((i + 1) / totalQuestions) * 100);
            dom.pptLoadingProgressBar.style.width = `${progress}%`;
            dom.pptLoadingDetails.textContent = `Processing question ${slide_question_number} of ${totalQuestions}... (${progress}%)`;

            if (i % 10 === 0) await new Promise(resolve => setTimeout(resolve, 0));

            // SLIDE 1: QUESTION & OPTIONS
            let q_slide = pptx.addSlide({ bkgd: QUESTION_SLIDE_BG });
            
            let question_text = (question_item.question || '').split(')').slice(1).join(')').trim();
            q_slide.addText(`Q.${slide_question_number}) ${question_text}`, {
                x: 0.5, y: 0.3, w: 9, h: 0.8,
                fontFace: ENGLISH_FONT, fontSize: 20, color: TEXT_COLOR, bold: true
            });

            q_slide.addText(question_item.question_hi || '', {
                x: 0.5, y: 1.3, w: 9, h: 0.6,
                fontFace: HINDI_FONT, fontSize: 18, color: TEXT_COLOR, bold: true
            });

            let optionsY = 2.1;
            let optionsArray = [];
            (question_item.options || []).forEach((eng_option, index) => {
                const hin_option = (question_item.options_hi || [])[index] || '';
                const option_letter = String.fromCharCode(65 + index);
                optionsArray.push({
                    text: `${option_letter}) ${eng_option}`,
                    options: { fontFace: ENGLISH_FONT, fontSize: 16, color: TEXT_COLOR }
                });
                optionsArray.push({
                    text: `    ${hin_option}\n`,
                    options: { fontFace: HINDI_FONT, fontSize: 14, color: TEXT_COLOR, breakLine: true }
                });
            });
            q_slide.addText(optionsArray, { x: 0.6, y: optionsY, w: 9, h: 3.2, lineSpacing: 24 });


            // SLIDE 2 & 3: ANSWER & EXPLANATION
            const explanation = question_item.explanation || {};

            const slideParts = [
                {
                    part: 1,
                    title: `Answer & Explanation for Q.${slide_question_number} (Part 1)`,
                    content: [
                        { text: `✅ Correct Answer: ${question_item.correct || 'N/A'}`, style: { fontFace: ENGLISH_FONT, bold: true, fontSize: 16, color: CORRECT_ANSWER_COLOR }, spaceAfter: 16 },
                        parseExplanation(explanation.analysis_correct),
                        parseExplanation(explanation.conclusion),
                    ]
                },
                {
                    part: 2,
                    title: `Answer & Explanation for Q.${slide_question_number} (Part 2)`,
                    content: [
                        parseExplanation(explanation.analysis_incorrect),
                        parseExplanation(explanation.fact),
                    ]
                }
            ];

            slideParts.forEach(partInfo => {
                let aSlide = pptx.addSlide({ bkgd: ANSWER_SLIDE_BG });
                aSlide.addText(partInfo.title, { x: 0.5, y: 0.3, w: 9, h: 0.6, fontFace: ENGLISH_FONT, fontSize: 18, color: TEXT_COLOR, bold: true });

                let currentY = 1.1;
                partInfo.content.forEach(block => {
                    if (block.text) { // For the hardcoded 'Correct Answer' line
                        aSlide.addText(block.text, { x: 0.5, y: currentY, w: 9, h: 0.5, ...block.style });
                        currentY += 0.5 + (block.spaceAfter / 72 || 0.2);
                    } else if (block.heading) { // For parsed explanation blocks
                        // Add Heading
                        aSlide.addText(block.heading, {
                            x: 0.5, y: currentY, w: 9, h: 0.4,
                            fontFace: ENGLISH_FONT, fontSize: 15, bold: true, color: TEXT_COLOR
                        });
                        currentY += 0.45;

                        // Add Body
                        const cleanedBody = block.body.replace(/^- /gm, '').replace(/\*\*/g, '');
                        const lines = cleanedBody.split('\n').length;
                        const bodyHeight = Math.max(0.4, lines * 0.3);
                        aSlide.addText(cleanedBody, {
                            x: 0.6, y: currentY, w: 8.8, h: bodyHeight,
                            fontFace: ENGLISH_FONT, fontSize: 13, color: TEXT_COLOR,
                            italic: block.heading.includes('Note') || block.heading.includes('Fact')
                        });
                        currentY += bodyHeight + 0.3;
                    }
                });
            });
        }

        dom.pptLoadingText.textContent = 'Finalizing & Downloading...';
        dom.pptLoadingDetails.textContent = 'Please wait, this may take a moment.';
        await pptx.writeFile({ fileName: 'Quiz_LM_Presentation.pptx' });

    } catch (error) {
        console.error("Error generating PPT:", error);
        Swal.fire({
            target: dom.filterSection,
            title: 'Error',
            text: `An unexpected error occurred while generating the presentation: ${error.message}`,
            icon: 'error'
        });
    } finally {
        dom.pptLoadingOverlay.style.display = 'none';
    }
}


async function generatePDF() {
    const questions = state.filteredQuestionsMasterList;
    if (questions.length === 0) {
        Swal.fire({
            target: dom.filterSection,
            title: 'No Questions Selected',
            text: 'Please apply filters to select questions before creating a PDF.',
            icon: 'info'
        });
        return;
    }

    dom.pdfLoadingOverlay.style.display = 'flex';
    dom.pdfLoadingText.textContent = 'Preparing Your PDF...';
    dom.pdfLoadingDetails.textContent = '';
    dom.pdfLoadingProgressBar.style.width = '0%';

    try {
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF({
            orientation: 'p',
            unit: 'mm',
            format: 'a4'
        });

        // Add the custom font for Hindi support
        doc.addFileToVFS('NotoSansDevanagari-Regular.ttf', hindiFontBase64);
        doc.addFont('NotoSansDevanagari-Regular.ttf', 'NotoSansDevanagari', 'normal');
        doc.addFont('NotoSansDevanagari-Regular.ttf', 'NotoSansDevanagari', 'bold');

        const MARGIN = 15;
        const PAGE_WIDTH = doc.internal.pageSize.getWidth();
        const PAGE_HEIGHT = doc.internal.pageSize.getHeight();
        const MAX_WIDTH = PAGE_WIDTH - MARGIN * 2;
        let y = MARGIN + 10;
        const answers = [];

        // --- Title Page ---
        doc.setFontSize(22);
        doc.setFont('Helvetica', 'bold');
        doc.text("Quiz LM Question Bank", PAGE_WIDTH / 2, y, { align: 'center' });
        y += 15;
        doc.setFontSize(14);
        doc.setFont('Helvetica', 'normal');
        doc.text(`A custom set of ${questions.length} questions.`, PAGE_WIDTH / 2, y, { align: 'center' });
        y += 10;
        doc.setLineWidth(0.5);
        doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
        y += 10;

        // Print Applied Filters
        doc.setFontSize(12);
        doc.setFont('Helvetica', 'bold');
        doc.text("Applied Filters:", MARGIN, y);
        y += 7;
        doc.setFontSize(10);
        doc.setFont('Helvetica', 'normal');
        let filtersApplied = false;
        Object.keys(state.selectedFilters).forEach(key => {
            if (state.selectedFilters[key] && state.selectedFilters[key].length > 0) {
                filtersApplied = true;
                const filterName = key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1').trim();
                const filterValues = state.selectedFilters[key].join(', ');
                const text = `${filterName}: ${filterValues}`;
                const lines = doc.splitTextToSize(text, MAX_WIDTH);
                if (y + (lines.length * 5) > PAGE_HEIGHT - MARGIN) {
                    doc.addPage();
                    y = MARGIN;
                }
                doc.text(lines, MARGIN, y);
                y += (lines.length * 5) + 3;
            }
        });
        if (!filtersApplied) {
            doc.text("No filters applied (All questions included).", MARGIN, y);
        }
        
        doc.addPage();
        y = MARGIN + 10;

        const totalQuestions = questions.length;

        for (let i = 0; i < totalQuestions; i++) {
            const question_item = questions[i];
            const slide_question_number = i + 1;

            const progress = Math.round(((i + 1) / totalQuestions) * 100);
            dom.pdfLoadingProgressBar.style.width = `${progress}%`;
            dom.pdfLoadingDetails.textContent = `Processing question ${slide_question_number} of ${totalQuestions}... (${progress}%)`;

            if (i % 10 === 0) await new Promise(resolve => setTimeout(resolve, 0));
            
            let questionText = `Q.${slide_question_number}) ${question_item.question || ''}`;
            let questionHiText = question_item.question_hi || '';
            let optionsEng = question_item.options || [];
            let optionsHin = question_item.options_hi || [];
            let correctEng = question_item.correct || '';

            const estimateHeight = () => {
                let h = 0;
                h += doc.splitTextToSize(questionText, MAX_WIDTH).length * 6;
                h += doc.splitTextToSize(questionHiText, MAX_WIDTH).length * 5;
                h += 10;
                optionsEng.forEach((opt, idx) => {
                    h += doc.splitTextToSize(`(${String.fromCharCode(65 + idx)}) ${opt}`, MAX_WIDTH).length * 5;
                    if (optionsHin[idx]) {
                         h += doc.splitTextToSize(optionsHin[idx], MAX_WIDTH).length * 5;
                    }
                    h += 3;
                });
                return h;
            };

            if (y + estimateHeight() > PAGE_HEIGHT - MARGIN) {
                doc.addPage();
                y = MARGIN + 10;
            }
            
            // English Question
            doc.setFontSize(12);
            doc.setFont('Helvetica', 'bold');
            doc.setTextColor(0, 0, 0);
            let lines = doc.splitTextToSize(questionText, MAX_WIDTH);
            doc.text(lines, MARGIN, y);
            y += lines.length * 6;
            
            // Hindi Question
            doc.setFont('NotoSansDevanagari', 'bold');
            doc.setTextColor(0, 0, 255); // Blue
            doc.setFontSize(11);
            lines = doc.splitTextToSize(questionHiText, MAX_WIDTH);
            doc.text(lines, MARGIN, y);
            y += (lines.length * 5) + 5;
            
            // Options
            doc.setFontSize(10);
            optionsEng.forEach((opt, idx) => {
                const isCorrect = opt.trim() === correctEng.trim();
                const optionLetter = String.fromCharCode(65 + idx);
                
                if (isCorrect) {
                    const originalQuestionNum = question_item.question.split(')')[0];
                    answers.push(`${slide_question_number} (${originalQuestionNum}): ${optionLetter}) ${correctEng}`);
                }
                
                // English Option
                doc.setFont('Helvetica', 'normal');
                doc.setTextColor(0, 0, 0);
                lines = doc.splitTextToSize(`(${optionLetter}) ${opt}`, MAX_WIDTH - 5);
                doc.text(lines, MARGIN + 5, y);
                y += lines.length * 5;
                
                // Hindi Option
                if (optionsHin[idx]) {
                    doc.setFont('NotoSansDevanagari', 'bold');
                    doc.setTextColor(0, 0, 255);
                    lines = doc.splitTextToSize(optionsHin[idx], MAX_WIDTH - 10);
                    doc.text(lines, MARGIN + 10, y);
                    y += lines.length * 5;
                }
                
                y += 3;
            });
            
            y += 10;
            doc.setLineWidth(0.2);
            doc.setDrawColor(200);
            doc.line(MARGIN, y - 5, PAGE_WIDTH - MARGIN, y - 5);
        }
        
        // --- Answer Key Page ---
        doc.addPage();
        y = MARGIN + 10;
        doc.setFontSize(16);
        doc.setFont('Helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text("Answer Key", PAGE_WIDTH / 2, y, { align: 'center' });
        y += 15;

        doc.setFontSize(10);
        doc.setFont('Helvetica', 'normal');
        for (const answer of answers) {
            const lines = doc.splitTextToSize(answer, MAX_WIDTH);
            if (y + (lines.length * 5) > PAGE_HEIGHT - MARGIN) {
                doc.addPage();
                y = MARGIN;
            }
            doc.text(lines, MARGIN, y);
            y += (lines.length * 5) + 2;
        }

        // Add Footer to all pages
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(9);
            doc.setTextColor(150);
            // Left Footer
            doc.text('Compiler :- Aalok Kumar Sharma', MARGIN, PAGE_HEIGHT - (MARGIN / 2));
            // Center Footer
            doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH / 2, PAGE_HEIGHT - (MARGIN / 2), { align: 'center' });
        }

        dom.pdfLoadingText.textContent = 'Finalizing & Downloading...';
        dom.pdfLoadingDetails.textContent = 'Please wait, this may take a moment.';
        
        await doc.save('Quiz_LM_Custom_PDF.pdf');

    } catch (error) {
        console.error("Error generating PDF:", error);
        Swal.fire({
            target: dom.filterSection,
            title: 'Error',
            text: `An unexpected error occurred while generating the PDF: ${error.message}`,
            icon: 'error'
        });
    } finally {
        dom.pdfLoadingOverlay.style.display = 'none';
    }
}


function toggleMultiSelectDropdown(filterKey, forceClose = false) {
    const dropdown = dom.filterElements[filterKey]?.dropdown;
    if (!dropdown) return;
    const isVisible = dropdown.style.display === 'flex';
    if (forceClose) {
        dropdown.style.display = 'none';
    } else {
        dropdown.style.display = isVisible ? 'none' : 'flex';
    }
}

function filterMultiSelectList(filterKey) {
    const elements = dom.filterElements[filterKey];
    if (!elements || !elements.searchInput || !elements.list) return;

    const searchTerm = elements.searchInput.value.toLowerCase();
    elements.list.querySelectorAll('.multiselect-item').forEach(label => {
        const itemText = label.querySelector('span:not(.filter-option-count)').textContent.trim().toLowerCase();
        label.style.display = itemText.includes(searchTerm) ? 'flex' : 'none';
    });
}

function updateMultiSelectButtonText(filterKey) {
    const toggleBtn = dom.filterElements[filterKey]?.toggleBtn;
    if (!toggleBtn || toggleBtn.disabled) return;

    const selected = state.selectedFilters[filterKey] || [];
    const count = selected.length;
    const labelText = dom.filterElements[filterKey].container.previousElementSibling.textContent;

    if (count === 0) {
        let plural = labelText.endsWith('s') ? labelText : labelText + 's';
        toggleBtn.textContent = `Select ${plural}`;
    } else if (count === 1) {
        toggleBtn.textContent = selected[0];
    } else {
        let plural = labelText.endsWith('s') ? labelText : labelText + 's';
        toggleBtn.textContent = `${count} ${plural} Selected`;
    }
}

function updateActiveFiltersSummaryBar() {
    dom.activeFiltersSummaryBar.innerHTML = '';
    let totalSelected = 0;
    config.filterKeys.forEach(key => {
        const selected = state.selectedFilters[key] || [];
        totalSelected += selected.length;
        selected.forEach(value => {
            const tag = document.createElement('span');
            tag.className = 'filter-tag';
            tag.textContent = value;
            
            const closeBtn = document.createElement('button');
            closeBtn.className = 'tag-close-btn';
            closeBtn.innerHTML = '&times;';
            closeBtn.setAttribute('aria-label', `Remove ${value} filter`);
            closeBtn.onclick = () => handleSelectionChange(key, value);
            
            tag.appendChild(closeBtn);
            dom.activeFiltersSummaryBar.appendChild(tag);
        });
    });
    dom.activeFiltersSummaryBarContainer.style.display = totalSelected > 0 ? 'block' : 'none';
}

function handleQuickStart(preset) {
    resetFilters();
    
    switch(preset) {
        case 'quick_25_easy':
            state.selectedFilters.difficulty = ['Easy'];
            break;
        case 'quick_25_moderate':
            state.selectedFilters.difficulty = ['Medium'];
            break;
        case 'quick_25_hard':
            state.selectedFilters.difficulty = ['Hard'];
            break;
        case 'quick_25_mix':
            // No filter applied, will use all questions
            break;
    }
    applyFilters();
    
    shuffleArray(state.filteredQuestionsMasterList);
    state.filteredQuestionsMasterList = state.filteredQuestionsMasterList.slice(0, 25);

    if (state.filteredQuestionsMasterList.length === 0) {
        Swal.fire({
            target: dom.filterSection,
            title: 'No Questions Found', 
            text: 'This quick start preset yielded no questions. Please try another or use the custom filters.', 
            icon: 'warning'
        });
        resetFilters();
        return;
    }

    startFilteredQuiz();
}
